using System.Windows;

namespace Hud.App.Services
{
    public static class LocalizationManager
    {
        private const string DefaultLanguage = "Espanol";

        private static readonly string[] SupportedLanguages =
        {
            "Espanol", "English", "Francais", "Portugues", "Deutsch"
        };

        private static readonly Dictionary<string, Dictionary<string, string>> Dictionaries = BuildDictionaries();

        public static string CurrentLanguage { get; private set; } = DefaultLanguage;

        public static IReadOnlyList<string> Languages => SupportedLanguages;

        public static void Apply(string? language)
        {
            CurrentLanguage = NormalizeLanguage(language);
            var resources = Application.Current?.Resources;
            if (resources is null)
                return;

            foreach (var key in Dictionaries[DefaultLanguage].Keys)
                resources[key] = Text(key);
        }

        public static string Text(string key)
        {
            if (Dictionaries.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var value))
                return value;

            return Dictionaries[DefaultLanguage].TryGetValue(key, out var fallback) ? fallback : key;
        }

        public static string NormalizeLanguage(string? language)
        {
            if (string.IsNullOrWhiteSpace(language))
                return DefaultLanguage;

            var clean = language.Trim();
            var lower = clean.ToLowerInvariant();
            if (lower.Contains("fran"))
                return "Francais";
            if (lower.Contains("portugu"))
                return "Portugues";
            if (lower.Contains("espa"))
                return "Espanol";
            if (lower.Contains("deut") || lower.Contains("german") || lower.Contains("alem"))
                return "Deutsch";
            if (lower.Contains("engl") || lower.Contains("ingl"))
                return "English";

            return lower switch
            {
                "spanish" or "espanol" or "español" => "Espanol",
                "english" or "ingles" or "inglés" => "English",
                "francais" or "français" or "french" or "frances" or "francés" => "Francais",
                "portugues" or "português" or "portuguese" => "Portugues",
                "deutsch" or "german" or "aleman" or "alemán" => "Deutsch",
                _ => SupportedLanguages.FirstOrDefault(x => string.Equals(x, clean, StringComparison.OrdinalIgnoreCase)) ?? DefaultLanguage
            };
        }

        private static Dictionary<string, Dictionary<string, string>> BuildDictionaries()
        {
            var es = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["App.Title"] = "APH - Analyzer Poker Hands",
                ["Main.Subtitle"] = "Menu principal",
                ["Main.GlobalStats"] = "GLOBAL STATS",
                ["Main.SelectFolderHint"] = "Selecciona una carpeta con historiales para calcular stats promedio.",
                ["Main.HeroProfileTip"] = "Abrir perfil del heroe",
                ["Main.PickFolderTip"] = "Seleccionar carpeta de manos",
                ["Main.SettingsTip"] = "Configuracion",
                ["Main.RecentTables"] = "MESAS RECIENTES",
                ["Main.RealTime"] = "Tiempo real",
                ["Main.OpenRT"] = "Iniciar analizador RT (8)",
                ["Main.Waiting"] = "(Esperando seleccion...)",
                ["Main.HistoryAnalysis"] = "Analisis de historial",
                ["Main.TablesAnalysis"] = "Analisis por mesas",
                ["Main.TablesAnalysisDesc"] = "Ganancias y KPIs separados por mesa",
                ["Main.MyTables"] = "Mis Tablas",
                ["Main.MyTablesDesc"] = "Mapa de acciones por mano inicial",
                ["Main.DataVillains"] = "Data Villans",
                ["Main.DataVillainsDesc"] = "Rivales recientes y bb contra ellos",
                ["Main.LeakFinder"] = "Detector de leaks",
                ["Main.LeakFinderDesc"] = "Encuentra patrones donde pierdes bb",
                ["Grid.Player"] = "Jugador",
                ["Grid.Hands"] = "#Manos",
                ["Grid.Table"] = "Mesa",
                ["Grid.Format"] = "Formato",
                ["Grid.Date"] = "Fecha",
                ["Grid.FinalBb"] = "BB final",
                ["Settings.Title"] = "APH - Configuracion",
                ["Settings.Header"] = "Configuracion",
                ["Settings.Subtitle"] = "Preferencias generales, carpeta de PokerStars, idioma, paletas y sincronizacion futura.",
                ["Settings.PokerStars"] = "PokerStars",
                ["Settings.PokerStarsDesc"] = "Carpeta predefinida de historiales. La app la carga automaticamente al iniciar.",
                ["Settings.FolderLabel"] = "Carpeta de hand histories",
                ["Settings.Search"] = "Buscar",
                ["Settings.Language"] = "Idioma",
                ["Settings.LanguageDesc"] = "El idioma se aplica y guarda al cambiarlo.",
                ["Settings.LanguageLabel"] = "Idioma de la aplicacion",
                ["Settings.Palette"] = "Paleta de colores",
                ["Settings.PaletteDesc"] = "El tema se aplica y guarda al cambiarlo.",
                ["Settings.PaletteLabel"] = "Tema visual",
                ["Settings.PalettePreview"] = "Vista previa de paletas",
                ["Settings.PalettePreviewDesc"] = "Classic Poker es la actual; las otras cambian el ambiente visual.",
                ["Settings.Sync"] = "Sincronizacion",
                ["Settings.SyncDesc"] = "Preparado para nube, Google y correo. Por ahora queda como modulo futuro.",
                ["Settings.Cloud"] = "Sincronizar nube",
                ["Settings.Google"] = "Google",
                ["Settings.Email"] = "Correo",
                ["Settings.Soon"] = "Proximamente",
                ["Settings.Status"] = "Los cambios de idioma y color se guardan al instante.",
                ["Settings.Cancel"] = "Cerrar",
                ["Settings.Save"] = "Guardar carpeta",
                ["RT.Title"] = "APH - Tiempo real (8)",
                ["RT.HelpTip"] = "Abrir ayuda de Tiempo real",
                ["RT.Compact"] = "Modo compacto",
                ["RT.CompactDesc"] = "(reduce tamanos y escala para mostrar todo sin desplazamiento)",
                ["RT.Header"] = "Tiempo real - 8 mesas",
                ["RT.Detect"] = "Detectar mesas",
                ["RT.DetectHint"] = "Pulsa Detectar mesas para enlazar ventanas PokerStars con sus historiales. Tambien puedes usar + manualmente.",
                ["RT.DictionarySubtitle"] = "Controles, colores y metricas usadas mientras las mesas se leen en vivo.",
                ["Global.Title"] = "APH - Analisis por mesas",
                ["Global.Header"] = "ANALISIS POR MESAS",
                ["Global.Table"] = "Mesa",
                ["Global.Date"] = "Fecha",
                ["Global.Blinds"] = "Ciegas",
                ["Global.Format"] = "Formato",
                ["Global.Result"] = "Resultado",
                ["Global.MinHands"] = "Min. manos",
                ["Global.Type"] = "Tipo",
                ["Global.Sort"] = "Orden",
                ["Global.OpenTableTip"] = "Abrir analisis de esta mesa",
                ["Common.Search"] = "Buscar",
                ["Common.DateTime"] = "Fecha/Hora",
                ["Common.RecentTable"] = "Mesa reciente",
                ["Common.SessionVs"] = "Vs sesion",
                ["Common.TotalVs"] = "Total-Vs",
                ["Common.TotalHands"] = "Total manos",
                ["Common.Profile"] = "Perfil",
                ["Common.SessionBb"] = "BB sesion",
                ["Common.TotalBb"] = "BB total",
                ["Common.LoadedTables"] = "Mesas cargadas",
                ["Common.AnalyzedHands"] = "Manos analizadas",
                ["Common.TotalResult"] = "Resultado total",
                ["Common.BiggestLeak"] = "Mayor fuga",
                ["Common.CriticalHands"] = "Manos criticas",
                ["Common.PositionLosses"] = "PERDIDAS POR POSICION",
                ["Common.RealEvByAction"] = "EV REAL POR ACCION",
                ["Common.PotType"] = "TIPO DE BOTE",
                ["Common.ProblemHands"] = "MANOS PROBLEMATICAS",
                ["Common.BoardTexture"] = "BOARD TEXTURE",
                ["Common.CompareSessions"] = "COMPARAR SESIONES",
                ["Common.ReviewHands"] = "MANOS PARA REVISAR",
                ["Common.ViewAll"] = "Ver todo",
                ["Common.WorstHand"] = "Peor mano",
                ["Common.MostExpensiveAction"] = "Accion mas cara",
                ["Common.MostExpensivePot"] = "Bote mas caro",
                ["Common.Sample"] = "Muestra",
                ["Common.Hands"] = "Manos",
                ["Common.Average"] = "Media",
                ["Common.Action"] = "Accion",
                ["Common.Position"] = "Posicion",
                ["Common.Result"] = "Resultado",
                ["Common.Type"] = "Tipo",
                ["Common.Sort"] = "Orden",
                ["Common.Blinds"] = "Ciegas",
                ["Common.From"] = "Desde",
                ["Common.To"] = "Hasta",
                ["Common.Color"] = "Color",
                ["Common.ProfitBb"] = "Ganancia bb",
                ["Common.SelectCell"] = "Selecciona una celda",
                ["Common.ExactHands"] = "Manos exactas",
                ["Common.All"] = "Todas",
                ["Common.AllMale"] = "Todos",
                ["Common.Won"] = "Ganadas",
                ["Common.Lost"] = "Perdidas",
                ["Common.BestHands"] = "MEJORES MANOS",
                ["Common.WorstHands"] = "PEORES MANOS",
                ["Common.QuickRead"] = "LECTURA RAPIDA",
                ["Common.PositionProfit"] = "GANANCIA Y JUEGO POR POSICION",
                ["Common.TopCombos"] = "TOP 10 COMBOS QUE MAS JUEGA",
                ["Common.EvByAction"] = "EV POR ACCION",
                ["Common.Cards"] = "Cartas",
                ["Common.Combo"] = "Combo",
                ["Common.TableAnalysisTitle"] = "APH - Analisis de mesa",
                ["Common.HandsTitle"] = "MANOS",
                ["Common.ProfitChart"] = "GRAFICA DE GANANCIA / PERDIDA",
                ["Common.HeroProfileTitle"] = "APH - Perfil del heroe",
                ["Common.OpenDictionary"] = "Abrir diccionario de tags y colores",
                ["Common.BestPosition"] = "Mejor posicion",
                ["Common.WorstPosition"] = "Peor posicion",
                ["Common.ProfileDictionaryTitle"] = "APH - Diccionario del perfil",
                ["Common.VillainDictionaryTitle"] = "APH - Diccionario de villanos",
                ["Common.RealTimeHelpTitle"] = "APH - Ayuda de Tiempo real",
                ["Common.Dictionary"] = "DICCIONARIO",
                ["Common.Tags"] = "TAGS",
                ["Common.MetricColors"] = "COLORES DE METRICAS",
                ["Common.TableColors"] = "COLORES DE TABLAS",
                ["Common.StatMeaning"] = "QUE MIDE CADA STAT",
                ["Common.Controls"] = "CONTROLES",
                ["Common.DataVillainsTitle"] = "APH - Data Villans",
                ["Common.LeakFinderTitle"] = "APH - Detector de leaks",
                ["Common.LeakSpotsTitle"] = "APH - Spots de leak",
                ["Common.Villain"] = "Villano",
                ["Common.Recent"] = "Reciente",
                ["Common.Note"] = "Nota",
                ["Common.WorstSpot"] = "Peor spot",
                ["Common.Texture"] = "Textura",
                ["Common.Pot"] = "Bote",
                ["Common.DictionarySubtitleVillains"] = "Tags, tablas del villano y colores usados en estadisticas y rangos.",
                ["Common.DictionarySubtitleProfile"] = "Tags, lectura rapida y colores usados en las metricas globales.",
                ["Common.DictionaryMetrics"] = "DICCIONARIO DE METRICAS",
                ["Common.ProfileDictionaryHeader"] = "DICCIONARIO DEL PERFIL",
                ["Common.VillainDictionaryHeader"] = "DICCIONARIO DE VILLANOS",
                ["Common.RealTimeHelpHeader"] = "AYUDA DE TIEMPO REAL",
                ["Common.HeroVsVillain"] = "HEROE VS VILLANO",
                ["Common.AllData"] = "ALL DATA",
                ["Common.SampleSummary"] = "RESUMEN DE MUESTRA",
                ["Common.BaseProfile"] = "Perfil base",
                ["Common.RecentFormat"] = "Formato reciente",
                ["Common.ColorByProfitBb"] = "Color por ganancia bb",
                ["Common.VillainTables"] = "TABLAS DEL VILLANO (MUESTRA CONOCIDA)",
                ["Common.SelectComboExact"] = "Selecciona una combinacion para ver manos exactas",
                ["Common.TableName"] = "Mesa",
                ["Common.TableHand"] = "Mano mesa",
                ["Common.ExactHand"] = "Mano exacta",
                ["Common.FinalBoard"] = "Board final",
                ["Common.MyTablesHeader"] = "MIS TABLAS",
                ["Common.Lines"] = "Lineas:",
                ["Common.Last"] = "Ultima:",
                ["Common.Hero"] = "Heroe",
                ["Common.LastNine"] = "Ultimas 9",
                ["Common.Sequence"] = "Secuencia",
                ["Common.TablePlaceholder"] = "(mesa)",
                ["Common.StatusSelectFolderGlobal"] = "Selecciona una carpeta primero para cargar el analisis por mesas.",
                ["Common.StatusGlobalOpen"] = "Analisis por mesas abierto.",
                ["Common.StatusSelectFolderTables"] = "Selecciona una carpeta primero para cargar Mis Tablas.",
                ["Common.StatusTablesOpen"] = "Mis Tablas abierto.",
                ["Common.StatusSelectFolderVillains"] = "Selecciona una carpeta primero para cargar Data Villans.",
                ["Common.StatusVillainsOpen"] = "Data Villans abierto.",
                ["Common.StatusSelectFolderLeaks"] = "Selecciona una carpeta primero para cargar Detector de leaks.",
                ["Common.StatusLeaksOpen"] = "Detector de leaks abierto.",
                ["Common.StatusSelectFolderHero"] = "Selecciona una carpeta primero para cargar el perfil del heroe.",
                ["Common.StatusHeroOpen"] = "Perfil de {0} abierto.",
                ["Common.StatusRtOpen"] = "Analizador RT abierto (8 mesas).",
                ["Common.SelectHandFolderTitle"] = "Selecciona la carpeta con historiales de manos",
                ["Common.SettingsSaved"] = "Configuracion guardada.",
                ["Common.AnalyzingFolder"] = "Analizando carpeta: {0}",
                ["Common.FolderAnalysisFailed"] = "No se pudo analizar la carpeta.",
                ["Common.AnalyzeErrorTitle"] = "Error al analizar",
                ["Common.SelectPokerStarsFolderTitle"] = "Selecciona la carpeta de historiales de PokerStars",
                ["Common.PreviewApplied"] = "Vista previa aplicada: {0}.",
                ["Common.RtNoWindows"] = "No encontre ventanas activas de PokerStars con mesas Hold'em.",
                ["Common.RtNoMatches"] = "Detecte mesa(s): {0}. No encontre HH recientes coincidentes en {1}.",
                ["Common.RtLinked"] = "Mesas enlazadas: {0}/{1}.",
                ["Common.RtStartedPartial"] = "RT iniciado en {0} mesa(s). {1} ventana(s) no tuvieron HH reciente coincidente.",
                ["Common.RtStartedComplete"] = "RT iniciado en {0} mesa(s) detectada(s).",
                ["Common.Chips"] = "Fichas",
                ["Filter.Last7"] = "Ultimos 7 dias",
                ["Filter.Last30"] = "Ultimos 30 dias",
                ["Filter.CurrentMonth"] = "Mes actual",
                ["Filter.Winning"] = "Ganadoras",
                ["Filter.Losing"] = "Perdedoras",
                ["Filter.Win100"] = "+100bb o mas",
                ["Filter.Loss100"] = "-100bb o peor",
                ["Filter.MostRecent"] = "Mas recientes",
                ["Filter.BbWin"] = "Mayor ganancia bb",
                ["Filter.BbLoss"] = "Mayor perdida bb",
                ["Filter.AmountWin"] = "Mayor ganancia fichas/dinero",
                ["Filter.AmountLoss"] = "Mayor perdida fichas/dinero",
                ["Filter.IWin"] = "Les gano",
                ["Filter.TheyWin"] = "Me ganan",
                ["Filter.Even"] = "Parejos",
                ["Filter.Plus50"] = "+50bb o mas",
                ["Filter.Plus10To50"] = "+10 a +50",
                ["Filter.Minus10To50"] = "-10 a -50",
                ["Filter.Minus50"] = "-50bb o peor",
                ["Filter.MostVsHero"] = "Mas manos vs heroe",
                ["Filter.BestVsMe"] = "Mayor ganancia vs mi",
                ["Filter.WorstVsMe"] = "Mayor perdida vs mi",
                ["Filter.HighVpip"] = "VPIP alto",
                ["Filter.High3Bet"] = "3Bet alto",
                ["Filter.Profits"] = "Ganancias",
                ["Filter.WorstFirst"] = "Peor primero",
                ["Filter.BestFirst"] = "Mejor primero",
                ["Filter.RecentDate"] = "Fecha reciente",
                ["Filter.OldDate"] = "Fecha antigua",
                ["Common.TotalVillains"] = "Villanos",
                ["Common.Folder"] = "Carpeta",
                ["Common.Files"] = "Archivos",
                ["Common.NoHandsDetected"] = "Sin manos detectadas",
                ["Common.ReviewSummary"] = "Resumen de las {0} peores manos detectadas. Pulsa Ver todo para abrir el listado tipo tracker.",
                ["Common.TotalVillainHands"] = "Manos totales villano",
                ["Common.HandsVsHero"] = "Manos vs Heroe",
                ["Common.KnownCards"] = "Cartas conocidas",
                ["Common.NoExactHands"] = "Sin manos exactas",
                ["Common.Preflop"] = "PRE-FLOP"
            };

            var en = Merge(es, English());

            return new(StringComparer.OrdinalIgnoreCase)
            {
                ["Espanol"] = es,
                ["English"] = en,
                ["Francais"] = Merge(en, French()),
                ["Portugues"] = Merge(en, Portuguese()),
                ["Deutsch"] = Merge(en, German())
            };
        }

        private static Dictionary<string, string> Merge(Dictionary<string, string> baseDict, Dictionary<string, string> overrides)
        {
            var result = new Dictionary<string, string>(baseDict, StringComparer.OrdinalIgnoreCase);
            foreach (var item in overrides)
                result[item.Key] = item.Value;
            return result;
        }

        private static Dictionary<string, string> English() => new(StringComparer.OrdinalIgnoreCase)
        {
            ["App.Title"] = "APH - Poker Hands Analyzer",
            ["Main.Subtitle"] = "Main menu",
            ["Main.SelectFolderHint"] = "Select a hand history folder to calculate average stats.",
            ["Main.HeroProfileTip"] = "Open hero profile",
            ["Main.PickFolderTip"] = "Select hand folder",
            ["Main.SettingsTip"] = "Settings",
            ["Main.RecentTables"] = "RECENT TABLES",
            ["Main.RealTime"] = "Real time",
            ["Main.OpenRT"] = "Start RT analyzer (8)",
            ["Main.Waiting"] = "(Waiting for selection...)",
            ["Main.HistoryAnalysis"] = "History analysis",
            ["Main.TablesAnalysis"] = "Table analysis",
            ["Main.TablesAnalysisDesc"] = "Winnings and KPIs by table",
            ["Main.MyTables"] = "My Tables",
            ["Main.MyTablesDesc"] = "Action map by starting hand",
            ["Main.DataVillainsDesc"] = "Recent rivals and bb against them",
            ["Main.LeakFinder"] = "Leak detector",
            ["Main.LeakFinderDesc"] = "Find patterns where you lose bb",
            ["Grid.Player"] = "Player",
            ["Grid.Hands"] = "#Hands",
            ["Grid.Table"] = "Table",
            ["Grid.Format"] = "Format",
            ["Grid.Date"] = "Date",
            ["Grid.FinalBb"] = "Final BB",
            ["Settings.Title"] = "APH - Settings",
            ["Settings.Header"] = "Settings",
            ["Settings.Subtitle"] = "General preferences, PokerStars folder, language, palettes and future sync.",
            ["Settings.PokerStarsDesc"] = "Default hand history folder. The app loads it automatically on startup.",
            ["Settings.FolderLabel"] = "Hand history folder",
            ["Settings.Search"] = "Browse",
            ["Settings.Language"] = "Language",
            ["Settings.LanguageDesc"] = "Language is applied and saved when changed.",
            ["Settings.LanguageLabel"] = "Application language",
            ["Settings.Palette"] = "Color palette",
            ["Settings.PaletteDesc"] = "The theme is applied and saved when changed.",
            ["Settings.PaletteLabel"] = "Visual theme",
            ["Settings.PalettePreview"] = "Palette preview",
            ["Settings.Sync"] = "Sync",
            ["Settings.SyncDesc"] = "Ready for cloud, Google and email. Future module for now.",
            ["Settings.Cloud"] = "Cloud sync",
            ["Settings.Email"] = "Email",
            ["Settings.Soon"] = "Coming soon",
            ["Settings.Status"] = "Language and color changes are saved instantly.",
            ["Settings.Cancel"] = "Close",
            ["Settings.Save"] = "Save folder",
            ["RT.Title"] = "APH - Real time (8)",
            ["RT.HelpTip"] = "Open Real Time help",
            ["RT.Compact"] = "Compact mode",
            ["RT.CompactDesc"] = "(reduces sizes and scale to show everything without scrolling)",
            ["RT.Header"] = "Real time - 8 tables",
            ["RT.Detect"] = "Detect tables",
            ["RT.DetectHint"] = "Press Detect tables to link PokerStars windows with hand histories. You can also use + manually.",
            ["RT.DictionarySubtitle"] = "Controls, colors and metrics used while live tables are being read.",
            ["Global.Title"] = "APH - Table analysis",
            ["Global.Header"] = "TABLE ANALYSIS",
            ["Global.Blinds"] = "Blinds",
            ["Global.Result"] = "Result",
            ["Global.MinHands"] = "Min. hands",
            ["Global.Type"] = "Type",
            ["Global.Sort"] = "Sort",
            ["Global.OpenTableTip"] = "Open this table analysis",
            ["Common.Search"] = "Search",
            ["Common.RecentTable"] = "Recent table",
            ["Common.TotalHands"] = "Total hands",
            ["Common.Profile"] = "Profile",
            ["Common.LoadedTables"] = "Loaded tables",
            ["Common.AnalyzedHands"] = "Analyzed hands",
            ["Common.TotalResult"] = "Total result",
            ["Common.BiggestLeak"] = "Biggest leak",
            ["Common.CriticalHands"] = "Critical hands",
            ["Common.ViewAll"] = "View all",
            ["Common.WorstHand"] = "Worst hand",
            ["Common.MostExpensiveAction"] = "Most expensive action",
            ["Common.MostExpensivePot"] = "Most expensive pot",
            ["Common.Sample"] = "Sample",
            ["Common.Hands"] = "Hands",
            ["Common.Average"] = "Average",
            ["Common.Action"] = "Action",
            ["Common.Position"] = "Position",
            ["Common.Result"] = "Result",
            ["Common.Type"] = "Type",
            ["Common.Sort"] = "Sort",
            ["Common.From"] = "From",
            ["Common.To"] = "To",
            ["Common.Color"] = "Color",
            ["Common.ProfitBb"] = "BB profit",
            ["Common.SelectCell"] = "Select a cell",
            ["Common.ExactHands"] = "Exact hands",
            ["Common.All"] = "All",
            ["Common.AllMale"] = "All",
            ["Common.Won"] = "Won",
            ["Common.Lost"] = "Lost",
            ["Common.BestHands"] = "BEST HANDS",
            ["Common.WorstHands"] = "WORST HANDS",
            ["Common.QuickRead"] = "QUICK READ",
            ["Common.Cards"] = "Cards",
            ["Common.TableAnalysisTitle"] = "APH - Table analysis",
            ["Common.HeroProfileTitle"] = "APH - Hero profile",
            ["Common.OpenDictionary"] = "Open tags and colors dictionary",
            ["Common.BestPosition"] = "Best position",
            ["Common.WorstPosition"] = "Worst position",
            ["Common.Villain"] = "Villain",
            ["Common.Note"] = "Note",
            ["Common.DictionarySubtitleVillains"] = "Tags, villain tables and colors used in stats and ranges.",
            ["Common.DictionarySubtitleProfile"] = "Tags, quick read and colors used in global metrics.",
            ["Common.DictionaryMetrics"] = "METRICS DICTIONARY",
            ["Common.ProfileDictionaryHeader"] = "PROFILE DICTIONARY",
            ["Common.VillainDictionaryHeader"] = "VILLAIN DICTIONARY",
            ["Common.HeroVsVillain"] = "HERO VS VILLAIN",
            ["Common.BaseProfile"] = "Base profile",
            ["Common.RecentFormat"] = "Recent format",
            ["Common.SelectComboExact"] = "Select a combination to see exact hands",
            ["Common.TableHand"] = "Table hand",
            ["Common.ExactHand"] = "Exact hand",
            ["Common.FinalBoard"] = "Final board",
            ["Common.Lines"] = "Lines:",
            ["Common.Last"] = "Last:",
            ["Common.Hero"] = "Hero:",
            ["Common.LastNine"] = "Last 9",
            ["Common.Sequence"] = "Sequence",
            ["Common.StatusSelectFolderGlobal"] = "Select a folder first to load table analysis.",
            ["Common.StatusGlobalOpen"] = "Table analysis opened.",
            ["Common.StatusSelectFolderTables"] = "Select a folder first to load My Tables.",
            ["Common.StatusTablesOpen"] = "My Tables opened.",
            ["Common.StatusSelectFolderVillains"] = "Select a folder first to load Data Villans.",
            ["Common.StatusVillainsOpen"] = "Data Villans opened.",
            ["Common.StatusSelectFolderLeaks"] = "Select a folder first to load Leak detector.",
            ["Common.StatusLeaksOpen"] = "Leak detector opened.",
            ["Common.StatusSelectFolderHero"] = "Select a folder first to load the hero profile.",
            ["Common.StatusHeroOpen"] = "Profile for {0} opened.",
            ["Common.SelectHandFolderTitle"] = "Select the hand history folder",
            ["Common.SettingsSaved"] = "Settings saved.",
            ["Common.AnalyzingFolder"] = "Analyzing folder: {0}",
            ["Common.FolderAnalysisFailed"] = "Could not analyze the folder.",
            ["Common.AnalyzeErrorTitle"] = "Analysis error",
            ["Common.SelectPokerStarsFolderTitle"] = "Select the PokerStars hand history folder",
            ["Common.PreviewApplied"] = "Preview applied: {0}.",
            ["Common.RtNoWindows"] = "No active PokerStars Hold'em table windows found.",
            ["Common.RtNoMatches"] = "Detected table(s): {0}. No matching recent HH found in {1}.",
            ["Common.PositionLosses"] = "LOSSES BY POSITION",
            ["Common.RealEvByAction"] = "REAL EV BY ACTION",
            ["Common.PotType"] = "POT TYPE",
            ["Common.ProblemHands"] = "PROBLEM HANDS",
            ["Common.BoardTexture"] = "BOARD TEXTURE",
            ["Common.CompareSessions"] = "COMPARE SESSIONS",
            ["Common.ReviewHands"] = "HANDS TO REVIEW",
            ["Common.PositionProfit"] = "PROFIT AND PLAY BY POSITION",
            ["Common.TopCombos"] = "TOP 10 MOST PLAYED COMBOS",
            ["Common.EvByAction"] = "EV BY ACTION",
            ["Common.HandsTitle"] = "HANDS",
            ["Common.ProfitChart"] = "PROFIT / LOSS CHART",
            ["Common.Dictionary"] = "DICTIONARY",
            ["Common.Tags"] = "TAGS",
            ["Common.MetricColors"] = "METRIC COLORS",
            ["Common.TableColors"] = "TABLE COLORS",
            ["Common.StatMeaning"] = "WHAT EACH STAT MEASURES",
            ["Common.Controls"] = "CONTROLS",
            ["Common.DictionaryMetrics"] = "METRICS DICTIONARY",
            ["Common.ProfileDictionaryHeader"] = "PROFILE DICTIONARY",
            ["Common.VillainDictionaryHeader"] = "VILLAIN DICTIONARY",
            ["Common.RealTimeHelpHeader"] = "REAL TIME HELP",
            ["Common.VillainTables"] = "VILLAIN TABLES (KNOWN SAMPLE)",
            ["Common.MyTablesHeader"] = "MY TABLES",
            ["Common.Chips"] = "Chips",
            ["Filter.Last7"] = "Last 7 days",
            ["Filter.Last30"] = "Last 30 days",
            ["Filter.CurrentMonth"] = "Current month",
            ["Filter.Winning"] = "Winning",
            ["Filter.Losing"] = "Losing",
            ["Filter.Win100"] = "+100bb or more",
            ["Filter.Loss100"] = "-100bb or worse",
            ["Filter.MostRecent"] = "Most recent",
            ["Filter.BbWin"] = "Biggest bb win",
            ["Filter.BbLoss"] = "Biggest bb loss",
            ["Filter.AmountWin"] = "Biggest chips/money win",
            ["Filter.AmountLoss"] = "Biggest chips/money loss",
            ["Filter.IWin"] = "I beat them",
            ["Filter.TheyWin"] = "They beat me",
            ["Filter.Even"] = "Even",
            ["Filter.Plus50"] = "+50bb or more",
            ["Filter.Plus10To50"] = "+10 to +50",
            ["Filter.Minus10To50"] = "-10 to -50",
            ["Filter.Minus50"] = "-50bb or worse",
            ["Filter.MostVsHero"] = "Most hands vs hero",
            ["Filter.BestVsMe"] = "Best result vs me",
            ["Filter.WorstVsMe"] = "Worst result vs me",
            ["Filter.HighVpip"] = "High VPIP",
            ["Filter.High3Bet"] = "High 3Bet",
            ["Filter.Profits"] = "Profits",
            ["Filter.WorstFirst"] = "Worst first",
            ["Filter.BestFirst"] = "Best first",
            ["Filter.RecentDate"] = "Recent date",
            ["Filter.OldDate"] = "Old date",
            ["Common.TotalVillains"] = "Villains",
            ["Common.Folder"] = "Folder",
            ["Common.Files"] = "Files",
            ["Common.NoHandsDetected"] = "No hands detected",
            ["Common.ReviewSummary"] = "Summary of the {0} worst detected hands. Press View all to open the tracker-style list.",
            ["Common.TotalVillainHands"] = "Total villain hands",
            ["Common.HandsVsHero"] = "Hands vs Hero",
            ["Common.KnownCards"] = "Known cards"
            ,["Common.NoExactHands"] = "No exact hands"
        };

        private static Dictionary<string, string> French() => new(StringComparer.OrdinalIgnoreCase)
        {
            ["App.Title"] = "APH - Analyseur de mains de poker",
            ["Main.Subtitle"] = "Menu principal",
            ["Main.RealTime"] = "Temps reel",
            ["Main.OpenRT"] = "Demarrer l'analyse RT (8)",
            ["Main.HistoryAnalysis"] = "Analyse de l'historique",
            ["Main.TablesAnalysis"] = "Analyse par tables",
            ["Main.TablesAnalysisDesc"] = "Gains et KPIs par table",
            ["Main.MyTables"] = "Mes tables",
            ["Main.MyTablesDesc"] = "Carte des actions par main initiale",
            ["Main.DataVillainsDesc"] = "Rivaux recents et bb contre eux",
            ["Main.LeakFinder"] = "Detecteur de leaks",
            ["Main.LeakFinderDesc"] = "Trouve les schemas ou tu perds des bb",
            ["Grid.Player"] = "Joueur",
            ["Grid.Hands"] = "#Mains",
            ["Grid.Table"] = "Table",
            ["Grid.Format"] = "Format",
            ["Grid.Date"] = "Date",
            ["Settings.Title"] = "APH - Configuration",
            ["Settings.Header"] = "Configuration",
            ["Settings.Language"] = "Langue",
            ["Settings.Palette"] = "Palette de couleurs",
            ["Settings.Cancel"] = "Fermer",
            ["Settings.Save"] = "Enregistrer le dossier",
            ["RT.Title"] = "APH - Temps reel (8)",
            ["RT.Header"] = "Temps reel - 8 tables",
            ["RT.Detect"] = "Detecter les tables",
            ["RT.DictionarySubtitle"] = "Controles, couleurs et metriques utilisees pendant la lecture en direct des tables.",
            ["Global.Title"] = "APH - Analyse par tables",
            ["Global.Header"] = "ANALYSE PAR TABLES",
            ["Common.Result"] = "Resultat",
            ["Common.Type"] = "Type",
            ["Common.Sort"] = "Ordre",
            ["Common.Profile"] = "Profil",
            ["Common.Action"] = "Action",
            ["Common.Position"] = "Position",
            ["Common.SelectCell"] = "Selectionne une cellule",
            ["Common.ExactHands"] = "Mains exactes",
            ["Common.Won"] = "Gagnees",
            ["Common.Lost"] = "Perdues",
            ["Common.QuickRead"] = "LECTURE RAPIDE",
            ["Common.HeroProfileTitle"] = "APH - Profil du heros",
            ["Common.LoadedTables"] = "Tables chargees",
            ["Common.AnalyzedHands"] = "Mains analysees",
            ["Common.TotalResult"] = "Resultat total",
            ["Common.BiggestLeak"] = "Plus grande fuite",
            ["Common.CriticalHands"] = "Mains critiques",
            ["Common.PositionLosses"] = "PERTES PAR POSITION",
            ["Common.RealEvByAction"] = "EV REEL PAR ACTION",
            ["Common.PotType"] = "TYPE DE POT",
            ["Common.ProblemHands"] = "MAINS PROBLEMATIQUES",
            ["Common.BoardTexture"] = "TEXTURE DU BOARD",
            ["Common.CompareSessions"] = "COMPARER SESSIONS",
            ["Common.ReviewHands"] = "MAINS A REVOIR",
            ["Common.ViewAll"] = "Voir tout",
            ["Common.WorstHand"] = "Pire main",
            ["Common.MostExpensiveAction"] = "Action la plus couteuse",
            ["Common.MostExpensivePot"] = "Pot le plus couteux",
            ["Common.Sample"] = "Echantillon",
            ["Common.Hands"] = "Mains",
            ["Common.Average"] = "Moyenne",
            ["Common.Chips"] = "Jetons",
            ["Filter.Last7"] = "7 derniers jours",
            ["Filter.Last30"] = "30 derniers jours",
            ["Filter.CurrentMonth"] = "Mois actuel",
            ["Filter.Winning"] = "Gagnantes",
            ["Filter.Losing"] = "Perdantes",
            ["Filter.Win100"] = "+100bb ou plus",
            ["Filter.Loss100"] = "-100bb ou pire",
            ["Filter.MostRecent"] = "Plus recentes",
            ["Filter.BbWin"] = "Plus gros gain bb",
            ["Filter.BbLoss"] = "Plus grosse perte bb",
            ["Filter.AmountWin"] = "Plus gros gain jetons/argent",
            ["Filter.AmountLoss"] = "Plus grosse perte jetons/argent",
            ["Filter.IWin"] = "Je gagne",
            ["Filter.TheyWin"] = "Ils gagnent",
            ["Filter.Even"] = "Equilibre",
            ["Filter.Plus50"] = "+50bb ou plus",
            ["Filter.Plus10To50"] = "+10 a +50",
            ["Filter.Minus10To50"] = "-10 a -50",
            ["Filter.Minus50"] = "-50bb ou pire",
            ["Filter.MostVsHero"] = "Plus de mains vs heros",
            ["Filter.BestVsMe"] = "Meilleur resultat vs moi",
            ["Filter.WorstVsMe"] = "Pire resultat vs moi",
            ["Filter.HighVpip"] = "VPIP haut",
            ["Filter.High3Bet"] = "3Bet haut",
            ["Filter.Profits"] = "Gains",
            ["Filter.WorstFirst"] = "Pire d'abord",
            ["Filter.BestFirst"] = "Meilleur d'abord",
            ["Filter.RecentDate"] = "Date recente",
            ["Filter.OldDate"] = "Date ancienne"
        };

        private static Dictionary<string, string> Portuguese() => new(StringComparer.OrdinalIgnoreCase)
        {
            ["App.Title"] = "APH - Analisador de maos de poker",
            ["Main.Subtitle"] = "Menu principal",
            ["Main.RealTime"] = "Tempo real",
            ["Main.OpenRT"] = "Iniciar analisador RT (8)",
            ["Main.HistoryAnalysis"] = "Analise de historico",
            ["Main.TablesAnalysis"] = "Analise por mesas",
            ["Main.TablesAnalysisDesc"] = "Ganhos e KPIs por mesa",
            ["Main.MyTables"] = "Minhas mesas",
            ["Main.MyTablesDesc"] = "Mapa de acoes por mao inicial",
            ["Main.LeakFinder"] = "Detector de leaks",
            ["Main.LeakFinderDesc"] = "Encontra padroes onde voce perde bb",
            ["Grid.Player"] = "Jogador",
            ["Grid.Hands"] = "#Maos",
            ["Grid.Table"] = "Mesa",
            ["Grid.Format"] = "Formato",
            ["Grid.Date"] = "Data",
            ["Settings.Title"] = "APH - Configuracao",
            ["Settings.Header"] = "Configuracao",
            ["Settings.Language"] = "Idioma",
            ["Settings.Palette"] = "Paleta de cores",
            ["Settings.Cancel"] = "Fechar",
            ["Settings.Save"] = "Salvar pasta",
            ["RT.Title"] = "APH - Tempo real (8)",
            ["RT.Header"] = "Tempo real - 8 mesas",
            ["RT.Detect"] = "Detectar mesas",
            ["RT.DictionarySubtitle"] = "Controles, cores e metricas usadas enquanto as mesas sao lidas ao vivo.",
            ["Global.Title"] = "APH - Analise por mesas",
            ["Global.Header"] = "ANALISE POR MESAS",
            ["Common.Result"] = "Resultado",
            ["Common.Profile"] = "Perfil",
            ["Common.Action"] = "Acao",
            ["Common.Position"] = "Posicao",
            ["Common.SelectCell"] = "Selecione uma celula",
            ["Common.ExactHands"] = "Maos exatas",
            ["Common.Won"] = "Ganhas",
            ["Common.Lost"] = "Perdidas",
            ["Common.QuickRead"] = "LEITURA RAPIDA",
            ["Common.HeroProfileTitle"] = "APH - Perfil do heroi",
            ["Common.LoadedTables"] = "Mesas carregadas",
            ["Common.AnalyzedHands"] = "Maos analisadas",
            ["Common.TotalResult"] = "Resultado total",
            ["Common.BiggestLeak"] = "Maior leak",
            ["Common.CriticalHands"] = "Maos criticas",
            ["Common.PositionLosses"] = "PERDAS POR POSICAO",
            ["Common.RealEvByAction"] = "EV REAL POR ACAO",
            ["Common.PotType"] = "TIPO DE POTE",
            ["Common.ProblemHands"] = "MAOS PROBLEMATICAS",
            ["Common.BoardTexture"] = "TEXTURA DO BOARD",
            ["Common.CompareSessions"] = "COMPARAR SESSOES",
            ["Common.ReviewHands"] = "MAOS PARA REVISAR",
            ["Common.ViewAll"] = "Ver tudo",
            ["Common.WorstHand"] = "Pior mao",
            ["Common.MostExpensiveAction"] = "Acao mais cara",
            ["Common.MostExpensivePot"] = "Pote mais caro",
            ["Common.Sample"] = "Amostra",
            ["Common.Hands"] = "Maos",
            ["Common.Average"] = "Media",
            ["Common.Chips"] = "Fichas",
            ["Filter.Last7"] = "Ultimos 7 dias",
            ["Filter.Last30"] = "Ultimos 30 dias",
            ["Filter.CurrentMonth"] = "Mes atual",
            ["Filter.Winning"] = "Ganhadoras",
            ["Filter.Losing"] = "Perdedoras",
            ["Filter.Win100"] = "+100bb ou mais",
            ["Filter.Loss100"] = "-100bb ou pior",
            ["Filter.MostRecent"] = "Mais recentes",
            ["Filter.BbWin"] = "Maior ganho bb",
            ["Filter.BbLoss"] = "Maior perda bb",
            ["Filter.AmountWin"] = "Maior ganho fichas/dinheiro",
            ["Filter.AmountLoss"] = "Maior perda fichas/dinheiro",
            ["Filter.IWin"] = "Eu ganho",
            ["Filter.TheyWin"] = "Eles ganham",
            ["Filter.Even"] = "Empatado",
            ["Filter.Plus50"] = "+50bb ou mais",
            ["Filter.Plus10To50"] = "+10 a +50",
            ["Filter.Minus10To50"] = "-10 a -50",
            ["Filter.Minus50"] = "-50bb ou pior",
            ["Filter.MostVsHero"] = "Mais maos vs heroi",
            ["Filter.BestVsMe"] = "Melhor resultado vs mim",
            ["Filter.WorstVsMe"] = "Pior resultado vs mim",
            ["Filter.HighVpip"] = "VPIP alto",
            ["Filter.High3Bet"] = "3Bet alto",
            ["Filter.Profits"] = "Ganhos",
            ["Filter.WorstFirst"] = "Pior primeiro",
            ["Filter.BestFirst"] = "Melhor primeiro",
            ["Filter.RecentDate"] = "Data recente",
            ["Filter.OldDate"] = "Data antiga"
        };

        private static Dictionary<string, string> German() => new(StringComparer.OrdinalIgnoreCase)
        {
            ["App.Title"] = "APH - Pokerhand-Analyzer",
            ["Main.Subtitle"] = "Hauptmenu",
            ["Main.RealTime"] = "Echtzeit",
            ["Main.OpenRT"] = "RT-Analyse starten (8)",
            ["Main.HistoryAnalysis"] = "Historienanalyse",
            ["Main.TablesAnalysis"] = "Tischanalyse",
            ["Main.TablesAnalysisDesc"] = "Gewinne und KPIs pro Tisch",
            ["Main.MyTables"] = "Meine Tische",
            ["Main.MyTablesDesc"] = "Aktionskarte nach Starthand",
            ["Main.LeakFinder"] = "Leak-Detektor",
            ["Main.LeakFinderDesc"] = "Findet Muster, bei denen du bb verlierst",
            ["Grid.Player"] = "Spieler",
            ["Grid.Hands"] = "#Haende",
            ["Grid.Table"] = "Tisch",
            ["Grid.Format"] = "Format",
            ["Grid.Date"] = "Datum",
            ["Settings.Title"] = "APH - Einstellungen",
            ["Settings.Header"] = "Einstellungen",
            ["Settings.Language"] = "Sprache",
            ["Settings.Palette"] = "Farbpalette",
            ["Settings.Cancel"] = "Schliessen",
            ["Settings.Save"] = "Ordner speichern",
            ["RT.Title"] = "APH - Echtzeit (8)",
            ["RT.Header"] = "Echtzeit - 8 Tische",
            ["RT.Detect"] = "Tische erkennen",
            ["RT.DictionarySubtitle"] = "Steuerung, Farben und Metriken waehrend Live-Tische gelesen werden.",
            ["Global.Title"] = "APH - Tischanalyse",
            ["Global.Header"] = "TISCHANALYSE",
            ["Common.Result"] = "Ergebnis",
            ["Common.Profile"] = "Profil",
            ["Common.Action"] = "Aktion",
            ["Common.Position"] = "Position",
            ["Common.SelectCell"] = "Zelle auswaehlen",
            ["Common.ExactHands"] = "Exakte Haende",
            ["Common.Won"] = "Gewonnen",
            ["Common.Lost"] = "Verloren",
            ["Common.QuickRead"] = "SCHNELLANSICHT",
            ["Common.HeroProfileTitle"] = "APH - Hero-Profil",
            ["Common.LoadedTables"] = "Geladene Tische",
            ["Common.AnalyzedHands"] = "Analysierte Haende",
            ["Common.TotalResult"] = "Gesamtergebnis",
            ["Common.BiggestLeak"] = "Groesstes Leak",
            ["Common.CriticalHands"] = "Kritische Haende",
            ["Common.PositionLosses"] = "VERLUSTE NACH POSITION",
            ["Common.RealEvByAction"] = "REALER EV NACH AKTION",
            ["Common.PotType"] = "POTTYP",
            ["Common.ProblemHands"] = "PROBLEMHANDE",
            ["Common.BoardTexture"] = "BOARD TEXTURE",
            ["Common.CompareSessions"] = "SESSIONS VERGLEICHEN",
            ["Common.ReviewHands"] = "HANDE ZUR PRUEFUNG",
            ["Common.ViewAll"] = "Alle anzeigen",
            ["Common.WorstHand"] = "Schlechteste Hand",
            ["Common.MostExpensiveAction"] = "Teuerste Aktion",
            ["Common.MostExpensivePot"] = "Teuerster Pot",
            ["Common.Sample"] = "Stichprobe",
            ["Common.Hands"] = "Haende",
            ["Common.Average"] = "Durchschnitt",
            ["Common.Chips"] = "Chips",
            ["Filter.Last7"] = "Letzte 7 Tage",
            ["Filter.Last30"] = "Letzte 30 Tage",
            ["Filter.CurrentMonth"] = "Aktueller Monat",
            ["Filter.Winning"] = "Gewinner",
            ["Filter.Losing"] = "Verlierer",
            ["Filter.Win100"] = "+100bb oder mehr",
            ["Filter.Loss100"] = "-100bb oder schlechter",
            ["Filter.MostRecent"] = "Neueste",
            ["Filter.BbWin"] = "Groesster bb-Gewinn",
            ["Filter.BbLoss"] = "Groesster bb-Verlust",
            ["Filter.AmountWin"] = "Groesster Chip/Geld-Gewinn",
            ["Filter.AmountLoss"] = "Groesster Chip/Geld-Verlust",
            ["Filter.IWin"] = "Ich gewinne",
            ["Filter.TheyWin"] = "Sie gewinnen",
            ["Filter.Even"] = "Ausgeglichen",
            ["Filter.Plus50"] = "+50bb oder mehr",
            ["Filter.Plus10To50"] = "+10 bis +50",
            ["Filter.Minus10To50"] = "-10 bis -50",
            ["Filter.Minus50"] = "-50bb oder schlechter",
            ["Filter.MostVsHero"] = "Meiste Haende vs Hero",
            ["Filter.BestVsMe"] = "Bestes Ergebnis vs mich",
            ["Filter.WorstVsMe"] = "Schlechtestes Ergebnis vs mich",
            ["Filter.HighVpip"] = "Hoher VPIP",
            ["Filter.High3Bet"] = "Hoher 3Bet",
            ["Filter.Profits"] = "Gewinne",
            ["Filter.WorstFirst"] = "Schlechteste zuerst",
            ["Filter.BestFirst"] = "Beste zuerst",
            ["Filter.RecentDate"] = "Neuestes Datum",
            ["Filter.OldDate"] = "Aeltestes Datum"
        };
    }
}
